node.js
```js
Fun()

function Fun(){
  try{
    throw -100
  }catch(e){
    console.log(e +'')
  }
}
```
python
```py
def Fun():
    try:
        raise BaseException(-100) 
    except BaseException as e:
        print(e)

Fun()
```
C#
```cs
static void Fun()
{
    try
    {
        throw new Exception("-100");

    }catch(Exception e)
    {
        Console.WriteLine(e.ToString());
    }
}
```
C++
```cpp
void Fun() {
	try {
		throw "-100";
	}
	catch (const char* e) {
		cout << e << endl;
	}
}
```

# python 例外

python 使用 Exception Object 來表示例外。
如果例外物件未被捕捉，則會用 Traceback 來終止訊息。

python 所有例外都繼承 Exception
自 python2.5 之後，所有都改繼承 BaseException。
```py
try:
    open('./iaaaa.jpg')
except BaseException as ex:
    print('>>', ex)
```

BaseException 為所有類別例外可用。

```py
try:
    a = "Exception test"
    print(a)
except BaseException as ex:
    print('>>', ex)
else:
    print("There is no Exception")
```
可以在後方加上 else
無例外時執行
```py
try:
    a = "Exception test"
    print(a)
except BaseException as ex:
    print('>>', ex)
finally:
    print("Execute it, no matter what")
```
使用 finally
無論有無例外都會被執行

```py
def say_hi(name):
    if name is None:
        raise Exception('"name" cannot be empty')
    elif name == "":
        raise Exception('"name" cannot be ""')
    else:
        print("Hello %s" % name)
        
try:
    say_hi("")
except BaseException as ex:
    print(ex)
```
使用 raise 拋出例外物件

---

# python常見例外

* BaseException : 基礎例外類別
* Exception : 繼承自 BaseException
* AssertionError : assert(斷言) 敘述失敗
* FileNotFoundError : 開啟之檔案不存在
* AttributeError : 屬性讀取失敗
* OSError : 系統相關
* NameError : 使用未設定值物件的變數
* IndexError : 序列超出範圍
* SyntaxError : 解析器遇到語法錯誤
* KeyboardInterrupt : Ctrl+C 終止程式
* TypeError : 資料型別錯誤
